name: Docs

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.5.3

      - name: Set up Python 3.10 🔧
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies 🔧
        run: |
          cd docs/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd ..
          pip install e .

      - name: Build HTML 🔧
        run: |
          cd docs/
          make html
          touch _build/html/.nojekyll

      - name: Deploy Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages
          folder: docs/_build/html/
          clean: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
