name: "Code quality"

on: [push, pull_request]

jobs:

  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.5.3

      - name: Set up Python 🔧
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          pip install -e .['flake']

      - name: Test code quality 🔧
        run: |
          flake

lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
      - uses: actions/checkout@v3

      - name: Black codestyle 🔧
      - uses: psf/black@stable